#! /bin/bash

#Assign project argument
declare -i NUMARGS=$#
if [ $NUMARGS -eq 2 ]; then
    cpp_compiler=$1
    kokkos_dir=$2
else
    echo "ERROR: Expects exactly 2 arguments" 1>&2
    echo "  Usage: test-all <cpp-compiler> <kokkos-dir>" 1>&2
    exit 1
fi

set -e
set -x

mkdir test-all-build
cd test-all-build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$cpp_compiler -DKokkos_DIR=$kokkos_dir ..
make -j8
make baseline
OMP_NUM_THREADS=17 make test

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$cpp_compiler -DKokkos_DIR=$kokkos_dir -DDOUBLE_PRECISION=FALSE ..
make -j8
# no run

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$cpp_compiler -DKokkos_DIR=$kokkos_dir -DENABLE_TRACING=TRUE ..
make -j8
# no run

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$cpp_compiler -DKokkos_DIR=$kokkos_dir -DENABLE_TRACING=TRUE ..
make -j8
./p3/micro_sed 10000 128 300 30 1
./p3/micro_sed_vanilla 10000 128 300 30 1
./p3/micro_sed_vanilla_kokkos 10000 128 300 30 1
./p3/micro_sed_workspace_kokkos 10000 128 300 30 1
