#!/usr/bin/env python3

"""
Gather all performance data on all platforms of interest and store
them in a git branch.

It is expected that you are able to do a passwordless ssh to all
machines and that the given repo on the target machines are clean.
Since testbeds do not allow login via ssh key, you'll need to use kinit.
Waterman is on the SRN, so you'll need to start from a SRN machine. I've
had good luck using face.sandia.gov as my launch machine.

It is expected that your current repo is clean and that your current commit
is the one you want to test.
"""

from utils import expect, check_minimum_python_version, get_current_commit
check_minimum_python_version(3, 5)

import argparse, sys, os

from gather_all_data import GatherAllData, MACHINE_METADATA

###############################################################################
def parse_command_line(args, description):
###############################################################################
    parser = argparse.ArgumentParser(
        usage="""\n{0} <PERF-ANALYSIS-ARGS> [--verbose]
OR
{0} --help

\033[1mEXAMPLES:\033[0m
    \033[1;32m# Gather data \033[0m
    > {0} '64 128 300 30 10 $kokkos_install --cxx=$compiler -s "ni:2.0:16384" -n 10'
    # NOTE: leave the variables in the args unresolved so the script can resolve them

    \033[1;32m# Gather data for specific tests and specific machines \033[0m
    > {0} '64 128 300 30 10 $kokkos_install --cxx=$compiler -t ref -t final -s "ni:2.0:16384" -n 10' -m waterman -m bowman

    \033[1;32m# Do correctness testing instead of performance testing \033[0m
    > {0} -t

    \033[1;32m# Do correctness testing locally for SCREAM (expects ./scream and ./scream-docs) \033[0m
    > {0} -l -s -m $machine
""".format(os.path.basename(args[0])),
        description=description,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument("perf_analysis_args", nargs="?", help="Args to pass to perf_analysis")

    default_commit = get_current_commit(short=True)
    parser.add_argument("-c", "--commit", default=default_commit, help="Commit to test")

    parser.add_argument("-m", "--machine", action="append", choices=MACHINE_METADATA.keys(),
                        help="Select which machines to run on, default is all")

    parser.add_argument("-l", "--local", action="store_true",
                        help="Run tests on local machine")

    parser.add_argument("-t", "--test-all", action="store_true", help="Run test-all instead of performance gathering")

    parser.add_argument("-s", "--scream", action="store_true", help="Test scream instead of scream-docs. Implies --test-all")

    parser.add_argument("-s", "--scream", action="store_true", help="Test scream instead of scream-docs. Implies --test-all")

    parser.add_argument("-k", "--kokkos", help="Use to select specific kokkos installation.")

    parser.add_argument("--submit", action="store_true", help="Submit results to dashboard (scream-only).")

    args = parser.parse_args(args[1:])

    expect(not (args.local and len(args.machine) > 1),
           "Cannot run on multiple machines if local")

    if not args.machine:
        args.machine = MACHINE_METADATA.keys()

    if args.scream:
        args.test_all = True

    if args.submit:
        expect(args.scream, "Dashboard sumbission is only supported for scream")

    if not args.commit:
        expect(args.local, "Could not determine commit")
        args.commit = get_current_commit(short=True, repo="./scream") if args.scream else get_current_commit(short=True, repo="./scream-docs")

    return args.perf_analysis_args, args.commit, args.machine, args.test_all, args.scream, args.local, args.kokkos, args.submit

###############################################################################
def _main_func(description):
###############################################################################
    gad = GatherAllData(*parse_command_line(sys.argv, description))

    success = gad.gather_all_data()

    sys.exit(0 if success else 1)

###############################################################################

if (__name__ == "__main__"):
    _main_func(__doc__)
